# Generated by Django 5.0 on 2023-12-29 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 12, 0, 48, 733737)),
        ),
    ]
